name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # make sure pytest is available:
          pip install pytest

      - name: Smoke-test env var
        run: |
          python - <<EOF
          import os
          key = os.getenv("GOOGLE_API_KEY")
          if not key:
              raise RuntimeError("Missing key!")
          print("Got key length:", len(key))
          EOF

      - name: Run tests
        run: |
          pytest